# Site settings
title: Marta Sztybor | Front-end developer
email: hello@martasztybor.pl
description: "My personal blog, where I am focusing mostly on CSS"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martasztybor.pl" # the base hostname & protocol for your site
twitter_username: sztyborek
github_username:  sztyborek

# Build settings
markdown: kramdown
highlighter: null
