# Site settings
author: Marta Sztybor
title: I do front-end stuff
email: hello@martasztybor.pl
description: "My personal blog, where I am focusing mostly on CSS"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martasztybor.pl" # the base hostname & protocol for your site
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: martasztybor

# Social icons
github_username: sztyborek
bitbucket_username:
stackoverflow_id:
twitter_username: sztyborek
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Like it? Share it!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
